In [18]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [19]:
ts_c = tf.constant(2, name='ts_c')
ts_c

<tf.Tensor 'ts_c_2:0' shape=() dtype=int32>

In [20]:
ts_x = tf.Variable(ts_c+5, name='ts_x')
ts_x

<tf.Variable 'ts_x_2:0' shape=() dtype=int32_ref>

In [21]:
sess = tf.Session()

In [22]:
init = tf.compat.v1.global_variables_initializer()
sess.run(init)

In [23]:
print('ts_c= ', sess.run(ts_c))
print('ts_x= ', sess.run(ts_x))

ts_c=  2
ts_x=  7


In [24]:
print('ts_c= ', ts_c.eval(session=sess))
print('ts_x= ', ts_x.eval(session=sess))

ts_c=  2
ts_x=  7


In [25]:
sess.close()

In [26]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
ts_c = tf.constant(2, name='ts_c')
ts_x = tf.Variable(ts_c+5, name='ts_x')
with tf.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    print('ts_c= ', sess.run(ts_c))
    print('ts_x= ', sess.run(ts_x))
    

ts_c=  2
ts_x=  7


In [27]:
width=tf.placeholder('int32')
height=tf.placeholder('int32')
area=tf.multiply(width, height)
with tf.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    print('area= ', sess.run(area, feed_dict={width:6, height:8}))

area=  48


In [28]:
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/area', sess.graph)

In [29]:
ts_X = tf.Variable([0.4, 0.2, 0.4])
with tf.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)
print(X.shape)

[0.4 0.2 0.4]
(3,)


In [30]:
ts_X = tf.Variable([[0.4, 0.2, 0.4]])
with tf.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)
print(X.shape)

[[0.4 0.2 0.4]]
(1, 3)


In [38]:
W1 = tf.Variable([[-0.5, -0.2],[-0.3, 0.4], [-0.5, 0.2]])

with tf.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W1)
    print(W_array)
print(W_array.shape)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]
(3, 2)


In [39]:
W = tf.Variable([[-0.5, -0.2],[-0.3, 0.4], [-0.5, 0.2]])
X = tf.Variable([[1., 1., 1.]])
XW = tf.matmul(X,W)

with tf.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    XW_array = sess.run(XW)
    print(XW_array)
print(XW_array.shape)

[[-1.3  0.4]]
(1, 2)


In [41]:
b = tf.Variable([[0.1, 0.2]])
Sum = XW+b

with tf.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    print('Sum = ', sess.run(Sum))

Sum =  [[-1.1999999  0.6      ]]
